### ISSUE TITLE
yara -x rule clarity required

### ISSUE THREAD

**Issue by dexter0810** [Koodous/Koodous-issues#10]
yara -x androguard=d8adb784d08a951ebacf2491442cf90d21c20192085e44d1cd22e2b6bdd4ef5f-report.json rule.yar sample.apk
In this rule we test the rules written in the yar file with the json report generated and sample.apk contains random content? So, basically the json and yar file are the ones of importance?
Please correct me if I'm wrong.
Any help is much appreciated.

**Comment by Nekmo** [comment]
Sorry, we do not understand the question. Can you give us more details?

**Comment by dexter0810** [comment]
In the above question as per the commands on the Androguard github page, they first generated a json report and then tested these andopguard yara rules on it is where sample.apk just had random content. I could not understand the purpose of it there, the link is: 
https://github.com/Koodous/androguard-yara/blob/master/.travis.yml

**Comment by dexter0810** [comment]
Is there a way to simply test androguard yara rules on an app? I tried yara rule.yar sample.apk, that did not work. 

Any leads will be much appreciated. :)

**Comment by segura2010** [comment]
Hi @dexter0810 ! 
I am closing this issue since it is related to Androguard-Yara. I will try to reply to your question in the issue you created in the androguard-yara repository :)
