### ISSUE TITLE
Ruleset compilation error. "No module named yara"

### ISSUE THREAD

**Issue by locovich** [Koodous/Koodous-issues#14]
Hey, I'm trying to get a ruleset running but the error message in the title keeps showing up for me and preventing it from becoming active.

I'm using androguard and file modules, syntax looks ok compared to other running rulesets. I was unable to find much about the error message online and in Koodous docs, so filing this issue in hope that someone can shed some light into what is causing the error.

This is the ruleset (exactly as is below does trigger the error):

```
import "file"
import "androguard"

rule rosy_strings_plus_manifest
{
        meta:
        	description = "description"
		author = "me"

        strings:
            $s4 = "string4"
            $s3 = "string3"

        condition:
            ($s3 or $s4) and 
            ( 
                androguard.receiver("receiver") and
                androguard.filter("filter")
            )
}
```
The error message in the web (https://koodous.com/my_rulesets/{nnnn}) is exactly this: 
```
Ruleset compilation error. "No module named yara"
```
I'd appreciate any help you can provide to help me understand what's wrong and how to fix it.

**Comment by Nekmo** [comment]
Hi, there has been a issue creating our new machines and the Yara module is currently unavailable. This bug affects the creation of the new rules, the existing rules still work. We are working on it, sorry for the inconvenience.

**Comment by Nekmo** [comment]
Ok! it's finally in production. Sorry for the waiting :) 

Have a good day creating rules! :D
