### ISSUE TITLE
empty apk download links

### ISSUE THREAD

**Issue by nirmorgo** [Koodous/Koodous-issues#19]
When using the apk download api: https://api.koodous.com/apks/:sha256/download, I get an empty apk download link. 
the status code is 200 as if everything is fine, but the content is:{'download_url': None} (which is not very useful).
After a few attempts, I reach my daily download limit, and caמ't get any more links (status code: 429)

is it a problem on the server side or on my end?

**Comment by Nekmo** [comment]
This issue has been fixed. Thank you!

**Comment by nirmorgo** [comment]
awsome! thanks!
