### ISSUE TITLE
Analysis Strings pagination does not work

### ISSUE THREAD

**Issue by wesinator** [Koodous/Koodous-issues#2]
Firefox 64

**To reproduce:**
 - https://koodous.com/apks/3dcd7c32e9ea74b13590f59e3b91cf284065db5df21a3aa4f455782b7749e710/analysis Strings
 - Go to next pages of strings

All pages of strings show the same strings as the first.

Related to https://github.com/Koodous/Koodous-Angular-Client/issues/35

**Comment by Nekmo** [comment]
This is a UI bug. All requests use page 1.

![screenshot_20181230_013118](https://user-images.githubusercontent.com/740106/50543245-9d345100-0bd2-11e9-80df-c2ac9cdbce2e.png)

Thanks for your report! We will fix it as soon as possible :+1:
