### ISSUE TITLE
APK download API returns broken download links

### ISSUE THREAD

**Issue by nirmorgo** [Koodous/Koodous-issues#20]
Hi,
In the past few days, I have been trying to download some APK files using your API. It starting to get broken download links that are getting timed out.
It also happens with files that I have previously downloaded with no issues.
Can you please tell me if the problem is on the server-side, or on my end?
thanks!

**Comment by Nekmo** [comment]
We have already solved the problem, sorry for the inconvenience. :)

The problem was in warehouse. It has restarted and is now working.
