### ISSUE TITLE
REST Request only return 25 results

### ISSUE THREAD

**Issue by wiilauz56** [Koodous/Koodous-issues#21]
When i try to export my result with the rest api, i have only 25 results

my request :
import requests

headers = {"Authorization":"Token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
params = {'search': 'calculator.innovit.com.calculatrice  AND displayed_version:"1.3.1"  AND rating:<=-1'}
req = requests.get(url="https://api.koodous.com/apks", params=params, headers=headers)
koudous_json=req.json()
print(koudous_json)

i should have 55 results in my json response but i have only 25.

*******

i've tried this method and i've the same result :

URL = 'https://koodous.com/api/%s%s%s'

term='calculator.innovit.com.calculatrice AND displayed_version:"1.3.1" AND rating:<=-1)'
page=1
page_size=1000

url = URL % ('apks', '?search=%s&page=%i&page_size=%i' % (term, page, page_size), "" )
koudous=requests.get(url=url, headers=headers)
print(koudous.json())

**********

how to have all results ?

**Comment by Nekmo** [comment]
Hello,

In the documentation you have information about how to use the api.

https://docs.koodous.com/rest-api/apks/

Regards

**Comment by wiilauz56** [comment]
thanks but i didn't found any answer about why it doesn't return all.
i've tried with page and page_size but it only return 25 results

**Comment by Nekmo** [comment]
You need to paginate the results. At Koodous we have almost 58 million apks. We can't give you 58 million results in a single request. :)

**Comment by wiilauz56** [comment]
OK, i'll try, thanks
