### ISSUE TITLE
Trouble creating new accounts

### ISSUE THREAD

**Issue by cudi1999** [Koodous/Koodous-issues#26]
I cannot log in, and I cannot reset the password. I don’t receive the password reset link in the mailbox || And when I create a new account and the mail will be new, the mail tells me that you use another account? !! how can this be

**Comment by Nekmo** [comment]
Hi,

We are going to investigate this issue. Thanks!

**Comment by Nekmo** [comment]
There was a problem with the mail configuration. Already solved.

Thanks again!
