### ISSUE TITLE
Error in loggin and create account

### ISSUE THREAD

**Issue by Er1c-C** [Koodous/Koodous-issues#31]
Hi!
I am having problems creating a new account. When I enter any email I get "This email is currently being used by another account" or it doesn't let me create it.

If I use the password recovery option I don't receive anything by email either.

I wait for your answer, greetings

**Comment by Er1c-C** [comment]
up

**Comment by RubenEu** [comment]
Hey Bartosz! Thank you for getting in touch with us!

Contact us at info@koodous.com and send more information about what email are you trying to register.

Regards!
