### ISSUE TITLE
Certificate for *.koodous.com expired.

### ISSUE THREAD

**Issue by zyrikby** [Koodous/Koodous-issues#7]
Certificate for *.koodous.com expired. API calls through Python library cannot be executed.

I cannot connect to the end-point ceph.koodous.com

**Comment by Nekmo** [comment]
Thanks for reporting. I have assigned the issue :+1:

**Comment by alsdk** [comment]
SSL certificate has been updated on all koodous nodes.
Thanks for reporting.
